#!/usr/bin/python3
"""Module to define the Rectangle class"""

class Rectangle:
        """Class that defines a rectangle"""

            number_of_instances = 0
                """Number of instances of Rectangle"""

                    def __init__(self, width=0, height=0):
                                """Initialize a rectangle instance

                                        Args:
                                                        width (int): Width of the rectangle (default is 0)
                                                                    height (int): Height of the rectangle (default is 0)
                                                                            """
                                                                                    self.width = width
                                                                                            self.height = height
                                                                                                    Rectangle.number_of_instances += 1

                                                                                                        @property
                                                                                                            def width(self):
                                                                                                                    """Retrieve the width of the rectangle

                                                                                                                            Returns:
                                                                                                                                            int: Width of the rectangle
                                                                                                                                                    """
                                                                                                                                                            return self.__width

                                                                                                                                                                @width.setter
                                                                                                                                                                    def width(self, value):
                                                                                                                                                                            """Set the width of the rectangle

                                                                                                                                                                                    Args:
                                                                                                                                                                                                    value (int): Width value to be set

                                                                                                                                                                                                            Raises:
                                                                                                                                                                                                                            TypeError: If the width is not an integer
                                                                                                                                                                                                                                        ValueError: If the width is less than 0
                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                        if not isinstance(value, int):
                                                                                                                                                                                                                                                                    raise TypeError("width must be an integer")
                                                                                                                                                                                                                                                                            if value < 0:
                                                                                                                                                                                                                                                                                        raise ValueError("width must be >= 0")
                                                                                                                                                                                                                                                                                                self.__width = value

                                                                                                                                                                                                                                                                                                    @property
                                                                                                                                                                                                                                                                                                        def height(self):
                                                                                                                                                                                                                                                                                                                """Retrieve the height of the rectangle

                                                                                                                                                                                                                                                                                                                        Returns:
                                                                                                                                                                                                                                                                                                                                        int: Height of the rectangle
                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                        return self.__height

                                                                                                                                                                                                                                                                                                                                                            @height.setter
                                                                                                                                                                                                                                                                                                                                                                def height(self, value):
                                                                                                                                                                                                                                                                                                                                                                        """Set the height of the rectangle

                                                                                                                                                                                                                                                                                                                                                                                Args:
                                                                                                                                                                                                                                                                                                                                                                                                value (int): Height value to be set

                                                                                                                                                                                                                                                                                                                                                                                                        Raises:
                                                                                                                                                                                                                                                                                                                                                                                                                        TypeError: If the height is not an integer
                                                                                                                                                                                                                                                                                                                                                                                                                                    ValueError: If the height is less than 0
                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not isinstance(value, int):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise TypeError("height must be an integer")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if value < 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise ValueError("height must be >= 0")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.__height = value

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def area(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Calculate the area of the rectangle

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int: Area of the rectangle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return self.width * self.height

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def perimeter(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Calculate the perimeter of the rectangle

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int: Perimeter of the rectangle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 2 * (self.width + self.height)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def __str__(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Return a string representation of the rectangle

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        str: String representation of the rectangle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if self.width == 0 or self.height == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rectangle_str = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for _ in range(self.height):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rectangle_str += "#" * self.width + "\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return rectangle_str.rstrip()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def __repr__(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Return a string representation of the rectangle

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            str: String representation of the rectangle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return f"Rectangle({self.width}, {self.height})"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def __del__(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Destructor for the Rectangle class

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Prints a message and decrements the number_of_instances attribute.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Rectangle.number_of_instances -= 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Bye rectangle...")

